const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function item(title,desc,meta='',right=''){return `<div class="item"><div class="row"><div class="name">${esc(title)}</div><div>${right}</div></div>${desc?`<div class="desc">${esc(desc)}</div>`:''}${meta?`<div class="meta">${esc(meta)}</div>`:''}</div>`}
function statusClass(s=''){s=String(s).toLowerCase();return /pass|complete|supported|green|verified|active|clean|healthy|accepted/.test(s)?'green':/fail|reject|blocked|red|stop|critical|overdue/.test(s)?'red':'yellow'}
function label(x,prefix=''){return x.public_label||x.name||x.semantic_name||x.title||x.purpose||x.slug||prefix||'Unnamed'}
function bytes(n){n=Number(n||0);const u=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function render(d){$('title').textContent=d.meta?.title||'Research Dashboard';$('objective').textContent=d.status?.objective||'';$('phase').innerHTML=`Phase: <b>${esc(d.status?.phase||'unknown')}</b>`;$('health').innerHTML=`Health: <b class="${statusClass(d.status?.health)}">${esc(d.status?.health||'unknown')}</b>`;$('gate').textContent=`Next: ${d.status?.next_gate||'—'}`;$('updated').textContent=`Updated ${d.meta?.updated_at||'—'}`;
$('status').innerHTML=item('Current focus',d.status?.focus||'No focus set',`Owner: ${d.status?.owner||'—'}`)+item('Blocking uncertainty',d.status?.blocking_uncertainty||'None recorded',`Suite ${d.meta?.suite_version||'—'}`)+item('Progress',`${d.status?.progress||0}% toward next gate`,'',`<span class="score">${esc(d.status?.progress||0)}%</span><div class="bar"><i style="width:${Number(d.status?.progress||0)}%"></i></div>`);
const routes=d.routes||[];$('routes-count').textContent=routes.length;$('routes').innerHTML=routes.map(x=>item(label(x),x.hypothesis||x.summary||'',`${x.status||''} · kill: ${x.kill_criterion||'—'}`,`<span class="score">${esc(x.score??'—')}</span>`)).join('')||item('No routes','Run research-route-evaluator.');
const actions=d.human_actions||[];$('actions-count').textContent=actions.length;$('actions').innerHTML=actions.map(x=>item(label(x),x.detail||'',`${x.priority||'normal'} · ${x.owner||'human'} · ${x.status||'open'}`,`<span class="${statusClass(x.priority==='high'?'red':'yellow')}">●</span>`)).join('')||item('No pending actions','');
const props=d.capability_proposals||[];$('proposals-count').textContent=props.filter(x=>!['dismissed','completed'].includes(x.status)).length;$('proposals').innerHTML=props.map(x=>item(`${x.skill||'capability'}${x.mode?` / ${x.mode}`:''}`,x.benefit||x.reason||'',`${x.status||'recommended'} · approval: ${x.approval||'required'}`,`<span class="${statusClass(x.status==='approved'?'green':x.activation==='explicit_only'?'red':'yellow')}">${esc(x.context_cost||'')}</span>`)).join('')||item('No safeguard proposals','The orchestrator proposes consequential capabilities only at stage hinges.');
const ex=d.experiments||[];$('experiments-count').textContent=ex.length;$('experiments').innerHTML=`<table><thead><tr><th>Experiment</th><th>Purpose</th><th>Status</th><th>Result</th><th>Path</th></tr></thead><tbody>${ex.map(x=>`<tr><td>${esc(label(x))}</td><td>${esc(x.purpose||x.summary||'—')}</td><td class="${statusClass(x.status)}">${esc(x.status||'—')}</td><td>${esc(x.result||'—')}</td><td><code>${esc(x.path||'—')}</code></td></tr>`).join('')}</tbody></table>`;
const ag=d.agents||{};const profiles=ag.profiles||[];$('agents-count').textContent=`${ag.active_dispatches||0} active`;$('agents').innerHTML=item('Dispatch status',`${ag.active_dispatches||0} active; ${ag.completed||0} verified`,`${ag.failed||0} failed · ${ag.pending_evaluation||0} awaiting evaluation`)+profiles.map(x=>item(x.model||x.agent||'model',`${x.task_type||'mixed'} · quality ${x.quality??'—'} · success ${x.success_rate??'—'}`,`${x.observations||0} observations · uncertainty ${x.uncertainty||'high'}`,`<span class="score">${esc(x.cost_index??'—')}</span>`)).join('');
const ev=d.evidence||[];$('evidence-count').textContent=ev.length;$('evidence').innerHTML=ev.map(x=>item(label(x),x.summary||'',`${x.status||''} · ${x.kind||'evidence'}`,`<span class="${statusClass(x.status)}">${esc(x.coverage??'')}</span>`)).join('')||item('No evidence registered','Register evidence through the program evidence protocol.');
const st=d.storage||{};const w=st.worktrees||[];$('storage-count').textContent=bytes(st.total_bytes||0);$('storage').innerHTML=item('Artifact inventory',`${bytes(st.total_bytes||0)} total; ${bytes(st.cleanup_candidate_bytes||0)} candidate`,`${st.large_files||0} large files · last scan ${st.last_scan||'—'}`)+w.map(x=>item(x.name||x.path,x.purpose||'',`${x.status||'unknown'} · lease ${x.lease_expires||'—'}`,`<span class="${statusClass(x.status)}">${esc(x.dirty?'dirty':'clean')}</span>`)).join('');
const hy=d.hygiene||{};const hi=hy.items||[];$('hygiene-count').textContent=hy.open_items||0;$('hygiene').innerHTML=item('Repository state',`${hy.open_items||0} review items; ${hy.bare_public_ids||0} bare public IDs`,`${hy.temporary_tests||0} temporary tests · last scan ${hy.last_scan||'—'}`)+hi.map(x=>item(label(x),x.detail||'',`${x.kind||''} · ${x.status||'open'}`,`<span class="${statusClass(x.severity||x.status)}">●</span>`)).join('');
const lit=d.literature||{};const li=lit.items||[];$('literature-count').textContent=`${lit.included||0}/${lit.screened||0}`;$('literature').innerHTML=item('Screening',`${lit.screened||0} screened; ${lit.included||0} included`,`${lit.queries||0} query families`)+li.map(x=>item(label(x),x.relevance||'',`${x.year||''} · ${x.status||''}`)).join('');
const dec=[...(d.decisions||[]),...(d.risks||[])];$('decisions-count').textContent=dec.length;$('decisions').innerHTML=dec.map(x=>item(label(x),x.rationale||x.mitigation||'',`${x.status||x.severity||''} · ${x.owner||''}`)).join('')||item('No decisions/risks','');
const logs=d.logs||[];$('logs-count').textContent=logs.length;$('logs').innerHTML=logs.map(x=>item(x.event||x.text||'',x.detail||'',`${x.at||''} · ${x.actor||''}`)).join('')||item('No key logs','');}
fetch('project.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()}).then(render).catch(e=>{$('error').style.display='block';$('error').textContent=`Cannot load project.json: ${e}. Start dashboard.py serve instead of opening index.html directly.`});
