const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function item(title,desc,meta='',right=''){return `<div class="item"><div class="row"><div class="name">${esc(title)}</div><div>${right}</div></div>${desc?`<div class="desc">${esc(desc)}</div>`:''}${meta?`<div class="meta">${esc(meta)}</div>`:''}</div>`}
function statusClass(s=''){s=String(s).toLowerCase();return /pass|complete|supported|green|verified|active|clean|healthy|accepted|stable|calibrated/.test(s)?'green':/fail|reject|blocked|red|stop|critical|overdue|degrad|open-circuit/.test(s)?'red':'yellow'}
function label(x,prefix=''){return x.public_label||x.name||x.semantic_name||x.title||x.purpose||x.slug||prefix||'Unnamed'}
function bytes(n){n=Number(n||0);const u=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function money(x){if(x===null||x===undefined)return '—';return Number(x).toFixed(2)}
function render(d){$('title').textContent=d.meta?.title||'ResearchOps Dashboard';$('objective').textContent=d.status?.objective||'';$('phase').innerHTML=`Phase: <b>${esc(d.status?.phase||'unknown')}</b>`;$('health').innerHTML=`Health: <b class="${statusClass(d.status?.health)}">${esc(d.status?.health||'unknown')}</b>`;$('gate').textContent=`Next: ${d.status?.next_gate||'—'}`;$('updated').textContent=`Updated ${d.meta?.updated_at||'—'}`;
const intake=d.onboarding||{};const inf=intake.inference||{};const inv=intake.inventory||{};const mem=d.memory||{};const layerText=(mem.layers||[]).map(x=>`${x.layer}:${x.count}`).join(' · ');$('status').innerHTML=item('Current focus',d.status?.focus||'No focus set',`Owner: ${d.status?.owner||'—'}`)+item('Project intake',`${intake.adoption_mode||'unknown'} · inferred ${inf.phase||d.status?.phase||'unknown'} · confidence ${inf.confidence??'—'}`,`${inv.file_count||0} files scanned · ${intake.requires_agent_review?'review required':'initialized'}`)+item('Project memory',mem.available?`${mem.active||0} active memories`:'not initialized',mem.available?`${layerText||'no layers'} · sync ${mem.last_sync?.completed_at||'not yet'}`:'SQLite recall remains optional')+item('Blocking uncertainty',d.status?.blocking_uncertainty||'None recorded',`Suite ${d.meta?.suite_version||'—'}`)+item('Progress',`${d.status?.progress||0}% toward next gate`,'',`<span class="score">${esc(d.status?.progress||0)}%</span><div class="bar"><i style="width:${Number(d.status?.progress||0)}%"></i></div>`);
const routes=d.routes||[];$('routes-count').textContent=routes.length;$('routes').innerHTML=routes.map(x=>item(label(x),x.hypothesis||x.summary||'',`${x.status||''} · kill: ${x.kill_criterion||'—'}`,`<span class="score">${esc(x.score??'—')}</span>`)).join('')||item('No routes','Run research-route-evaluator.');
const actions=d.human_actions||[];$('actions-count').textContent=actions.length;$('actions').innerHTML=actions.map(x=>item(label(x),x.detail||'',`${x.priority||'normal'} · ${x.owner||'human'} · ${x.status||'open'}`,`<span class="${statusClass(x.priority==='high'?'red':'yellow')}">●</span>`)).join('')||item('No pending actions','');
const props=d.capability_proposals||[];$('proposals-count').textContent=props.filter(x=>!['dismissed','completed'].includes(x.status)).length;$('proposals').innerHTML=props.map(x=>item(`${x.skill||'capability'}${x.mode?` / ${x.mode}`:''}`,x.benefit||x.reason||'',`${x.status||'recommended'} · approval: ${x.approval||'required'}`,`<span class="${statusClass(x.status==='approved'?'green':x.activation==='explicit_only'?'red':'yellow')}">${esc(x.context_cost||'')}</span>`)).join('')||item('No safeguard proposals','');
const ex=d.experiments||[];$('experiments-count').textContent=ex.length;$('experiments').innerHTML=`<table><thead><tr><th>Experiment</th><th>Purpose</th><th>Status</th><th>Result</th><th>Path</th></tr></thead><tbody>${ex.map(x=>`<tr><td>${esc(label(x))}</td><td>${esc(x.purpose||x.summary||'—')}</td><td class="${statusClass(x.status)}">${esc(x.status||'—')}</td><td>${esc(x.result||'—')}</td><td><code>${esc(x.path||'—')}</code></td></tr>`).join('')}</tbody></table>`;
const mi=d.model_intelligence||{};const decisions=mi.recent_decisions||[];const outcomes=mi.recent_outcomes||[];const models=mi.model_summary||[];const warm=mi.warmup||[];const endpoints=mi.endpoint_health||[];$('intelligence-count').textContent=mi.available?`${models.length} models`:'offline';let intel='';if(!mi.available){intel=item('Model intelligence not initialized','Routing remains optional; initialize the SQLite control plane to enable this panel.')}else{const recent=decisions[0]?.summary_json||decisions[0]||{};if(recent.primary){intel+=item('Current preference',recent.primary.model_id||recent.selected_arm_id||'—',(recent.visible_reason||[]).join(' · '),`<span class="score">${esc(recent.primary.uncertainty||'')}</span>`)}intel+=outcomes.slice(0,3).map(x=>{const t=x.task_json||{};return item(t.objective||`${t.operation||'work unit'} · ${x.work_unit_id||x.task_id||'—'}`,`${x.execution_arm_id} · ${x.accepted?'accepted':'not accepted'} · progress ${Math.round(100*Number(x.verified_progress||0))}%`,`cost ${money(x.cost_amount)} ${x.currency||''} · quality ${Number(x.quality||0).toFixed(2)} · ${x.occurred_at||''}`,`<span class="${statusClass(x.accepted?'accepted':'failed')}">${x.accepted?'✓':'!'}</span>`)}).join('');intel+=warm.slice(0,4).map(x=>item(`${x.execution_arm_id} · ${x.operation}`,`${Math.round(100*Number(x.calibration_progress||x.rootedness||0))}% project adaptation`,`${x.status} · local ${x.local_observations||0} · inherited ${x.inherited_equivalent_observations||0}`,`<span class="${statusClass(x.status)}">${esc(x.status)}</span>`)).join('');intel+=models.slice(0,4).map(x=>item(x.execution_arm_id,`success ${x.success===null||x.success===undefined?'—':Number(x.success).toFixed(2)} · progress ${x.verified_progress===null||x.verified_progress===undefined?'—':Number(x.verified_progress).toFixed(2)} · ${x.observations||0} verified`,`median cost ${money(x.cost_median)} ${x.currency||''} · quality ${x.quality===null||x.quality===undefined?'—':Number(x.quality).toFixed(2)} · drift ${x.drift_status||'unknown'}`)).join('');intel+=endpoints.slice(0,3).map(x=>item(`Endpoint ${x.endpoint_id}`,`success ${Number(x.success_rate||0).toFixed(2)} · latency ${Number(x.latency_mean||0).toFixed(1)}s`,`last ${x.last_seen||'—'}`,`<span class="${statusClass((x.success_rate||0)>=.85?'healthy':(x.success_rate||0)>=.55?'degraded':'open-circuit')}">●</span>`)).join('')} $('intelligence').innerHTML=intel;
const ev=d.evidence||[];$('evidence-count').textContent=ev.length;$('evidence').innerHTML=ev.map(x=>item(label(x),x.summary||'',`${x.status||''} · ${x.kind||'evidence'}`,`<span class="${statusClass(x.status)}">${esc(x.coverage??'')}</span>`)).join('')||item('No evidence registered','Register evidence through the program evidence protocol.');
const st=d.storage||{};const w=st.worktrees||[];$('storage-count').textContent=bytes(st.total_bytes||0);$('storage').innerHTML=item('Artifact inventory',`${bytes(st.total_bytes||0)} total; ${bytes(st.cleanup_candidate_bytes||0)} candidate`,`${st.large_files||0} large files · last scan ${st.last_scan||'—'}`)+w.map(x=>item(x.name||x.path,x.purpose||'',`${x.status||'unknown'} · lease ${x.lease_expires||'—'}`,`<span class="${statusClass(x.status)}">${esc(x.dirty?'dirty':'clean')}</span>`)).join('');
const hy=d.hygiene||{};const hi=hy.items||[];$('hygiene-count').textContent=hy.open_items||0;$('hygiene').innerHTML=item('Repository state',`${hy.open_items||0} review items; ${hy.bare_public_ids||0} bare public IDs`,`${hy.temporary_tests||0} temporary tests · last scan ${hy.last_scan||'—'}`)+hi.map(x=>item(label(x),x.detail||'',`${x.kind||''} · ${x.status||'open'}`,`<span class="${statusClass(x.severity||x.status)}">●</span>`)).join('');
const lit=d.literature||{};const li=lit.items||[];$('literature-count').textContent=`${lit.included||0}/${lit.screened||0}`;$('literature').innerHTML=item('Screening',`${lit.screened||0} screened; ${lit.included||0} included`,`${lit.queries||0} query families`)+li.map(x=>item(label(x),x.relevance||'',`${x.year||''} · ${x.status||''}`)).join('');
const dec=[...(d.decisions||[]),...(d.risks||[])];$('decisions-count').textContent=dec.length;$('decisions').innerHTML=dec.map(x=>item(label(x),x.rationale||x.mitigation||'',`${x.status||x.severity||''} · ${x.owner||''}`)).join('')||item('No decisions/risks','');
const logs=d.logs||[];$('logs-count').textContent=logs.length;$('logs').innerHTML=logs.map(x=>item(x.event||x.text||'',x.detail||'',`${x.at||''} · ${x.actor||''}`)).join('')||item('No key logs','');}
async function refresh(){try{const r=await fetch(`view.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);render(await r.json());$('error').style.display='none'}catch(e){$('error').style.display='block';$('error').textContent=`Cannot load view.json: ${e}. Run dashboard.py start.`}}refresh();setInterval(refresh,10000);
